apiVersion: v1
kind: Service
metadata:
    name: exo2-service
spec:
    selector:
        app: exo2
    ports:
        -   port: 80
            protocol: TCP
            targetPort: 80
    type: LoadBalancer